name: CaptureTheFlag
version: '${project.version}'
main: mc.capturetheflag.CaptureTheFlag
api-version: 1.20
commands:
  join:
    description: Join a team
    usage: /join <team>
  leave:
    description: Leave a team
    usage: /leave

